trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      echo "Dependencies installed."
    displayName: 'Install dependencies'

  # Start app in the background just for build/test verification (not for prod deploy)
  - script: |
      nohup npm start > output.log 2>&1 &
      sleep 10
      echo "Started app, see output.log for details"
    displayName: 'Start Node.js app (background check)'

  - script: |
      curl -s http://localhost:3000/api/health || echo "Health endpoint check failed"
      cat output.log || echo "No output.log found"
    displayName: 'Verify app startup and print logs'
    continueOnError: true

  # Optional: Telegram notification on pipeline completion
  - bash: |
      MSG="Financebot pipeline completed on $(date '+%Y-%m-%d %H:%M:%S') for branch $(Build.SourceBranchName)"
      curl -s -X POST -H 'Content-Type: application/json' \
        -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MSG\"}" \
        https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage || true
    displayName: 'Send Telegram Notification'
    condition: always()
    env:
      TELEGRAM_BOT_TOKEN: $(TELEGRAM_BOT_TOKEN)
      TELEGRAM_CHAT_ID: $(TELEGRAM_CHAT_ID)
