trigger:
- master

variables:
- group: TradeBot keys    # Uses your secured secrets

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    # If you use React/Vue/Next/other frontend that needs a build step, uncomment the next line:
    # npm run build
  displayName: 'Install dependencies and build frontend (if any)'
  env:
    PERPLEXITY_API_KEY: $(PERPLEXITY_API_KEY)
    ALPHA_VANTAGE_API_KEY: $(ALPHA_VANTAGE_API_KEY)
    POLYGON_API_KEY: $(POLYGON_API_KEY)
    AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
    AZURE_OPENAI_KEY: $(AZURE_OPENAI_KEY)
    PORT: $(PORT)
    NODE_ENV: $(NODE_ENV)
    ALLOWED_ORIGINS: $(ALLOWED_ORIGINS)
    SESSION_TIMEOUT: $(SESSION_TIMEOUT)
    CACHE_TTL: $(CACHE_TTL)
    MAX_UPLOAD_SIZE: $(MAX_UPLOAD_SIZE)

- script: |
    npm start &
    sleep 5
    # Optionally, you can healthcheck your app here:
    # curl http://localhost:3000/health || echo "Healthcheck failed"
  displayName: 'Start server and smoke test'

- script: |
    echo "== Root directory =="
    ls -lh
    echo "== public =="
    ls -lh public || true
    echo "== build =="
    ls -lh build || true
    echo "== dist =="
    ls -lh dist || true
  displayName: 'List folders for debug'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'public'    # Change to build/dist if you have those after build step
    ArtifactName: 'app'
    publishLocation: 'Container'
  condition: succeededOrFailed()

- task: Bash@3
  displayName: 'Send Telegram Notification'
  inputs:
    targetType: 'inline'
    script: |
      BUILD_STATUS=$(if [ "$BUILD_BUILDSTATUS" == "Succeeded" ]; then echo "Succeeded"; else echo "Failed"; fi)
      DEPLOY_TIME=$(date +"%Y-%m-%d %H:%M:%S")
      COMMIT_AUTHOR=$(git log --format='%an' -n 1)
      COMMIT_MESSAGE=$(git log --format='%B' -n 1 | tr -d '\n"\\`')
      MSG="Azure deploy finished!\n\nDeploy details:\nBuild Status: $BUILD_STATUS\nPipeline: $BUILD_DEFINITIONNAME\nBranch: $BUILD_SOURCEBRANCHNAME\nDeploy Time: $DEPLOY_TIME\nCommit Author: $COMMIT_AUTHOR\nCommit Message: $COMMIT_MESSAGE\nTriggered by: $BUILD_REQUESTEDFOR\nURL: $BUILD_BUILDURI"
      curl -s -X POST \
        -H 'Content-Type: application/json' \
        -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MSG\"}" \
        https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage
  env:
    TELEGRAM_BOT_TOKEN: $(TELEGRAM_BOT_TOKEN)
    TELEGRAM_CHAT_ID: $(TELEGRAM_CHAT_ID)
    BUILD_BUILDSTATUS: $(Build.Status)
    BUILD_DEFINITIONNAME: $(Build.DefinitionName)
    BUILD_SOURCEBRANCHNAME: $(Build.SourceBranchName)
    BUILD_REQUESTEDFOR: $(Build.RequestedFor)
    BUILD_BUILDURI: $(Build.BuildUri)
  condition: always()

- script: |
    echo "Pipeline completed successfully! Artifacts ready for Azure App Service deployment."
  displayName: 'Finish: Log pipeline completion'
  condition: succeeded()
