version: '3.8'

services:
  financebot-pro:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: financebot-pro
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - PORT=3000
      - CHAT_RATE_LIMIT=${CHAT_RATE_LIMIT:-50}
      - UPLOAD_RATE_LIMIT=${UPLOAD_RATE_LIMIT:-10}
      - CACHE_TTL=${CACHE_TTL:-300000}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-2}
      - MAX_HOLDINGS=${MAX_HOLDINGS:-1000}
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Security
    user: "1001:1001"
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  # Development service (override for local development)
  financebot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: financebot-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    profiles:
      - dev

# Networks
networks:
  default:
    name: financebot-network

# Volumes for persistence
volumes:
  logs:
    driver: local