class KnowledgeBase {
    constructor() {
        this.financialTerms = {
            'stock': 'A share of ownership in a company that entitles the holder to a portion of the company\'s assets and profits.',
            'dividend': 'A payment made by corporations to shareholders, usually as a distribution of profits.',
            'pe ratio': 'Price-to-earnings ratio. A valuation ratio comparing a company\'s current share price to its per-share earnings.',
            'market cap': 'Market capitalization. The total value of a company\'s shares of stock.',
            'volatility': 'The degree of variation in a stock\'s price over time.',
            'bull market': 'A market condition where prices are rising or expected to rise.',
            'bear market': 'A market condition where prices are falling or expected to fall.',
            'ipo': 'Initial Public Offering. When a company first sells shares to the public.',
            'etf': 'Exchange-Traded Fund. A type of investment fund traded on stock exchanges.',
            'rsi': 'Relative Strength Index. A momentum oscillator measuring speed and magnitude of price changes.',
            'moving average': 'A calculation to analyze data points by creating averages of different subsets of data.',
            'support': 'A price level where a stock tends to find buying interest.',
            'resistance': 'A price level where a stock tends to find selling pressure.',
            'volume': 'The number of shares traded in a security during a given period.',
            'earnings': 'A company\'s profit or net income for a specific period.',
            'revenue': 'The total amount of income generated by a company from its operations.',
            'cryptocurrency': 'A digital or virtual currency secured by cryptography.',
            'blockchain': 'A distributed ledger technology underlying most cryptocurrencies.',
            'market order': 'An order to buy or sell immediately at the current market price.',
            'limit order': 'An order to buy or sell at a specific price or better.',
            'stop loss': 'An order to sell a security when it reaches a certain price.',
            'day trading': 'Buying and selling securities within the same trading day.',
            'swing trading': 'Holding positions for several days to weeks to profit from price swings.',
            'fundamental analysis': 'Evaluating a security by examining related economic and financial factors.',
            'technical analysis': 'Analyzing statistical trends from trading activity to evaluate investments.'
        };

        this.stockSymbols = {
            'AAPL': { name: 'Apple Inc.', sector: 'Technology', exchange: 'NASDAQ' },
            'MSFT': { name: 'Microsoft Corporation', sector: 'Technology', exchange: 'NASDAQ' },
            'GOOGL': { name: 'Alphabet Inc.', sector: 'Technology', exchange: 'NASDAQ' },
            'AMZN': { name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', exchange: 'NASDAQ' },
            'TSLA': { name: 'Tesla Inc.', sector: 'Consumer Discretionary', exchange: 'NASDAQ' },
            'META': { name: 'Meta Platforms Inc.', sector: 'Technology', exchange: 'NASDAQ' },
            'NVDA': { name: 'NVIDIA Corporation', sector: 'Technology', exchange: 'NASDAQ' },
            'INTC': { name: 'Intel Corporation', sector: 'Technology', exchange: 'NASDAQ' },
            'AMD': { name: 'Advanced Micro Devices', sector: 'Technology', exchange: 'NASDAQ' },
            'NFLX': { name: 'Netflix Inc.', sector: 'Communication Services', exchange: 'NASDAQ' },
            'PYPL': { name: 'PayPal Holdings Inc.', sector: 'Financial Services', exchange: 'NASDAQ' },
            'V': { name: 'Visa Inc.', sector: 'Financial Services', exchange: 'NYSE' },
            'MA': { name: 'Mastercard Inc.', sector: 'Financial Services', exchange: 'NYSE' },
            'WMT': { name: 'Walmart Inc.', sector: 'Consumer Staples', exchange: 'NYSE' },
            'JNJ': { name: 'Johnson & Johnson', sector: 'Healthcare', exchange: 'NYSE' },
            'PG': { name: 'Procter & Gamble Co.', sector: 'Consumer Staples', exchange: 'NYSE' },
            'KO': { name: 'Coca-Cola Co.', sector: 'Consumer Staples', exchange: 'NYSE' },
            'PEP': { name: 'PepsiCo Inc.', sector: 'Consumer Staples', exchange: 'NASDAQ' },
            'DIS': { name: 'Walt Disney Co.', sector: 'Communication Services', exchange: 'NYSE' },
            'BA': { name: 'Boeing Co.', sector: 'Industrials', exchange: 'NYSE' },
            'CAT': { name: 'Caterpillar Inc.', sector: 'Industrials', exchange: 'NYSE' },
            'GS': { name: 'Goldman Sachs Group Inc.', sector: 'Financial Services', exchange: 'NYSE' },
            'JPM': { name: 'JPMorgan Chase & Co.', sector: 'Financial Services', exchange: 'NYSE' },
            'BAC': { name: 'Bank of America Corp.', sector: 'Financial Services', exchange: 'NYSE' },
            'WFC': { name: 'Wells Fargo & Co.', sector: 'Financial Services', exchange: 'NYSE' },
            'BRK.B': { name: 'Berkshire Hathaway Inc.', sector: 'Financial Services', exchange: 'NYSE' }
        };

        this.cryptoSymbols = {
            'BTC': { name: 'Bitcoin', type: 'Cryptocurrency', maxSupply: 21000000 },
            'ETH': { name: 'Ethereum', type: 'Smart Contract Platform', maxSupply: null },
            'ADA': { name: 'Cardano', type: 'Smart Contract Platform', maxSupply: 45000000000 },
            'DOT': { name: 'Polkadot', type: 'Interoperability', maxSupply: null },
            'SOL': { name: 'Solana', type: 'Smart Contract Platform', maxSupply: null },
            'MATIC': { name: 'Polygon', type: 'Layer 2 Scaling', maxSupply: 10000000000 },
            'AVAX': { name: 'Avalanche', type: 'Smart Contract Platform', maxSupply: 720000000 },
            'LINK': { name: 'Chainlink', type: 'Oracle Network', maxSupply: 1000000000 },
            'UNI': { name: 'Uniswap', type: 'Decentralized Exchange', maxSupply: 1000000000 },
            'AAVE': { name: 'Aave', type: 'DeFi Lending', maxSupply: 16000000 }
        };

        this.marketIndices = {
            'SPY': { name: 'SPDR S&P 500 ETF', type: 'ETF', tracks: 'S&P 500' },
            'QQQ': { name: 'Invesco QQQ Trust', type: 'ETF', tracks: 'NASDAQ-100' },
            'IWM': { name: 'iShares Russell 2000 ETF', type: 'ETF', tracks: 'Russell 2000' },
            'VTI': { name: 'Vanguard Total Stock Market ETF', type: 'ETF', tracks: 'Total Stock Market' },
            'DIA': { name: 'SPDR Dow Jones Industrial Average ETF', type: 'ETF', tracks: 'Dow Jones' }
        };

        this.sectors = {
            'Technology': ['AAPL', 'MSFT', 'GOOGL', 'META', 'NVDA', 'INTC', 'AMD'],
            'Financial Services': ['V', 'MA', 'GS', 'JPM', 'BAC', 'WFC', 'BRK.B', 'PYPL'],
            'Consumer Discretionary': ['AMZN', 'TSLA'],
            'Consumer Staples': ['WMT', 'PG', 'KO', 'PEP'],
            'Healthcare': ['JNJ'],
            'Communication Services': ['NFLX', 'DIS'],
            'Industrials': ['BA', 'CAT']
        };
    }

    getFinancialTermDefinition(term) {
        const normalizedTerm = term.toLowerCase();
        return this.financialTerms[normalizedTerm] || null;
    }

    getStockInfo(symbol) {
        const upperSymbol = symbol.toUpperCase();
        return this.stockSymbols[upperSymbol] || null;
    }

    getCryptoInfo(symbol) {
        const upperSymbol = symbol.toUpperCase();
        return this.cryptoSymbols[upperSymbol] || null;
    }

    getSymbolType(symbol) {
        const upperSymbol = symbol.toUpperCase();
        
        if (this.stockSymbols[upperSymbol]) {
            return 'stock';
        }
        
        if (this.cryptoSymbols[upperSymbol]) {
            return 'crypto';
        }
        
        if (this.marketIndices[upperSymbol]) {
            return 'etf';
        }
        
        return 'unknown';
    }

    getSectorStocks(sector) {
        return this.sectors[sector] || [];
    }

    searchSymbols(query) {
        const normalizedQuery = query.toLowerCase();
        const results = [];

        // Search stock symbols and names
        for (const [symbol, info] of Object.entries(this.stockSymbols)) {
            if (symbol.toLowerCase().includes(normalizedQuery) || 
                info.name.toLowerCase().includes(normalizedQuery)) {
                results.push({ symbol, type: 'stock', ...info });
            }
        }

        // Search crypto symbols and names
        for (const [symbol, info] of Object.entries(this.cryptoSymbols)) {
            if (symbol.toLowerCase().includes(normalizedQuery) || 
                info.name.toLowerCase().includes(normalizedQuery)) {
                results.push({ symbol, type: 'crypto', ...info });
            }
        }

        return results;
    }

    getMarketHours() {
        return {
            nyse: {
                open: '09:30',
                close: '16:00',
                timezone: 'EST',
                premarket: '04:00-09:30',
                aftermarket: '16:00-20:00'
            },
            nasdaq: {
                open: '09:30',
                close: '16:00',
                timezone: 'EST',
                premarket: '04:00-09:30',
                aftermarket: '16:00-20:00'
            },
            crypto: {
                open: '24/7',
                close: '24/7',
                timezone: 'UTC'
            }
        };
    }

    isMarketOpen() {
        const now = new Date();
        const et = new Date(now.toLocaleString("en-US", {timeZone: "America/New_York"}));
        const hour = et.getHours();
        const minute = et.getMinutes();
        const day = et.getDay();
        
        // Weekend check
        if (day === 0 || day === 6) {
            return false;
        }
        
        // Market hours: 9:30 AM - 4:00 PM ET
        const marketOpen = 9.5; // 9:30 AM
        const marketClose = 16; // 4:00 PM
        const currentTime = hour + minute / 60;
        
        return currentTime >= marketOpen && currentTime < marketClose;
    }

    getEducationalContent(topic) {
        const content = {
            'investing_basics': 'Investing involves putting money into financial instruments with the expectation of profit. Key principles include diversification, risk management, and long-term thinking.',
            'risk_management': 'Risk management involves identifying, assessing, and controlling threats to capital and earnings. This includes diversification, stop losses, and position sizing.',
            'portfolio_diversification': 'Diversification spreads investments across various financial instruments, industries, and other categories to reduce exposure to any single asset or risk.',
            'dollar_cost_averaging': 'A strategy where you invest a fixed amount regularly regardless of market conditions, potentially reducing the impact of volatility.',
            'technical_analysis': 'The study of past market data, primarily price and volume, to forecast future price movements using charts and technical indicators.',
            'fundamental_analysis': 'Evaluating a security by examining related economic and financial factors to determine its intrinsic value.'
        };
        
        return content[topic] || null;
    }
}

module.exports = KnowledgeBase;